repos: 
- repo: local
  hooks:
    - id: fmt
      name: fmt
      description: Format files with cargo fmt.
      entry: bash
      language: system
      types: [rust]
      args: ["-c", "cargo +\"$(cat rust-toolchain.nightly)\" fmt --all -- --check"]
    - id: clippy
      name: clippy
      description: Lint rust sources
      entry: cargo clippy
      language: system
      args: ["--", "-W", "warnings"]
      types: [rust]
      pass_filenames: false